name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: oozz 
          key: ${{ secrets.GCP_SSH_KEY }}         # 개인키 PEM 내용 (-----BEGIN ~ -----END 까지 전부)
          script: |
            cd ~/upbitmonitor
            git pull origin main
            ./deploy.sh
