name: Deploy Alert to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ubuntu 
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/upbitmonitor
            git reset --hard HEAD
            git clean -fd
            git pull origin main
       



