name: Deploy Alert to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: oozz 
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/upbitmonitor
            mkdir -p logs
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            pkill -f alert.py || true   # 기존 alert.py 죽이기 (없어도 에러 무시)
            nohup python3 alert.py > logs/alert.log 2>&1 &


